# Generated by Django 4.2.7 on 2025-02-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_image_recipe_image_base64_and_more'),
        ('recipes', '0005_create_admin'),
    ]

    operations = [
    ]
